server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  front-url: http://127.0.0.1:3000
  claps-web-url: http://127.0.0.1:8080

spring:
  application:
    name: jobis_server
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/jobistest2
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  profiles:
    include: oauth



  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <GOOGLE_CLIENT_ID>
            clientSecret: <GOOGLE_CLIENT_SECRET>
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
jwt:
  token:
    header: api_key
    issuer: jobis_server
    clientSecret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
    expirySeconds: 0


app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BEEE
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080